server:
  port: 8082
  address: 127.0.0.1
  servlet:
    context-path: /bybit-integrator
  error:
    include-message: always
    include-binding-errors: always
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bitruby

spring:
  application:
    name: bybit-integrator
  liquibase:
    change-log: db/db.changelog.yaml
    liquibase-schema: bybit
  datasource:
    url: jdbc:postgresql://localhost:5432/bitruby?currentSchema=bybit
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: users
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      enable.idempotence: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "bitruby-bybit-integrator"
logging:
  level:
    org:
      springframework.security: trace
      springframework.web: trace
      apache:
        kafka: error
        http: DEBUG
        orm:
          jpa:
            JpaTransactionManager: trace
        transaction: trace
        listener:
          KafkaMessageListenerContainer: error


management:
  endpoints:
    web:
      exposure:
        include: '*'

bitruby:
  auth:
    url: http://auth-server:9000/auth/api/v1
  bybit:
    active: true
    bybit-api-secret: ''
    bybit-api-key: ''
    recvWindow: 50000
    url: ''
  kafka:
    topics:
      bybit:
        create-sub-account:
          name: "create-sub-account"
          numPartitions: 1
          replicationFactor: 1




