server:
  port: 8081
  address: 127.0.0.1
  servlet:
    context-path: /users
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: users-app
  liquibase:
    change-log: db/db.changelog-tenant.yaml
    liquibase-schema: users
  datasource:
    url: jdbc:postgresql://localhost:5432/bitruby?currentSchema=users
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: users
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      enable.idempotence: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "bitruby-users-app"
logging:
  level:

    org:
      springframework.web: trace
      apache:
        kafka: error
        orm:
          jpa:
            JpaTransactionManager: trace
        transaction: trace
        listener:
          KafkaMessageListenerContainer: error


management:
  endpoints:
    web:
      exposure:
        include: '*'

bitruby:
  kafka:
    topics:
      otp-login:
        name: "otp-login"
        numPartitions: 1
        replicationFactor: 1
      otp-registration:
        name: "otp-registration"
        numPartitions: 1
        replicationFactor: 1
      otp-restore-password:
        name: "otp-restore-password"
        numPartitions: 1
        replicationFactor: 1

