server:
  port: 8081
  address: 127.0.0.1
  servlet:
    context-path: /users
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: users-app
  datasource:
    url: jdbc:postgresql://localhost:5432/bitruby?currentSchema=users
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'

bitruby:
  users-app:
    complete-registration-url: http://127.0.0.1:4200/complete-registration
