server:
  port: 8081
  address: 127.0.0.1
  servlet:
    context-path: /users
  error:
    include-message: always
    include-binding-errors: always
  ssl:
    key-store: classpath:keystore.p12
    key-store-password:
    key-store-type: PKCS12
    key-alias: bitruby
spring:
  application:
    name: users-app
  liquibase:
    change-log: db/db.changelog.yaml
    liquibase-schema: users
  datasource:
    url: jdbc:postgresql://localhost:5432/bitruby?currentSchema=users
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: users
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      enable.idempotence: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: "bitruby-users-app"
logging:
  level:
    org:
      springframework.security: trace
      springframework.web: trace
      apache:
        kafka: error
        http: DEBUG
        orm:
          jpa:
            JpaTransactionManager: trace
        transaction: trace
        listener:
          KafkaMessageListenerContainer: error


management:
  endpoints:
    web:
      exposure:
        include: '*'

bitruby:
  auth:
    url: http://auth-server:9000/auth/api/v1
  verification:
    active: true
    secret-key:
    api-key:
    callback-url: 'https://webhook.cool/at/quaint-shampoo-70'
    url: 'https://stationapi.veriff.com/v1'
  kafka:
    topics:
      bybit:
        create-sub-account:
          name: "create-sub-account"
          numPartitions: 1
          replicationFactor: 1
      otp:
        login:
          name: "otp-login"
          numPartitions: 1
          replicationFactor: 1
        registration:
          name: "otp-registration"
          numPartitions: 1
          replicationFactor: 1
        restore-password:
          name: "otp-restore-password"
          numPartitions: 1
          replicationFactor: 1
      verification:
        events:
          name: "verification-events"
          numPartitions: 1
          replicationFactor: 1
        decisions:
          name: "verification-decisions"
          numPartitions: 1
          replicationFactor: 1
      notifications:
        user-verification-status:
          name: "user-verification-status"
          numPartitions: 1
          replicationFactor: 1



