spring:
  application:
    name: notifications-service
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      enable.idempotence: true
    consumer:
      group-id: "bitruby-notifications-service"
logging:
  level:
    org:
      springframework.web: trace
      springframework.security: trace
bitruby:
  smsTraffic:
    url: https://api.smstraffic.ru
    login: bitrubi
    password: CmBxYRTe
    active: true
  sendSay:
    active: true
    url: https://api.sendsay.ru/general/api/v100/json/
    apiKey: 18Wf7IhvBZ7ToE1IRdZk5uKpAg-pE6kPqlU8VhnP3Wcv8lde0xre4ttWJTq2k5JaU
    apiLogin: bitruby
    emailFrom: info@biruby.kg
  kafka:
    topics:
      otp:
        login:
          name: "otp-login"
          numPartitions: 1
          replicationFactor: 1
        registration:
          name: "otp-registration"
          numPartitions: 1
          replicationFactor: 1
        restore-password:
          name: "otp-restore-password"
          numPartitions: 1
          replicationFactor: 1
      notifications:
        user-verification-status:
          name: "user-verification-status"
          numPartitions: 1
          replicationFactor: 1

