networks:
  bitruby_net:
    driver: bridge
services:
  bitruby-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - bitruby_net
    container_name: bitruby-zookeeper

  bitruby-kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - bitruby-zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: bitruby-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bitruby-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bitruby_net
    container_name: bitruby-kafka

  bitruby-postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitruby
    networks:
      - bitruby_net
    container_name: bitruby-postgres

  bitruby-redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - bitruby_net
    container_name: bitruby-redis

  bitruby-fe-angular:
    image: bitruby-fe-angular:0.0.2
    ports:
      - 4200:4200
    container_name: bitruby-fe-angular

  bitruby-users-app:
    image: alexandershlyakhtin/users-app:0.0.4
    ports:
      - 8081:8081
    depends_on:
      - bitruby-postgres
      - bitruby-kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bitruby-postgres:5432/bitruby?currentSchema=users
      SPRING_KAFKA_BOOTSTRAP_SERVERS: bitruby-kafka:9092
      BITRUBY_AUTH_URL: http://bitruby-auth-server:9000/auth/api/v1
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://bitruby-auth-server:9000/auth/api/v1
      SERVER_SSL_KEY_STORE_PASSWORD: ${SERVER_SSL_KEY_STORE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SERVER_ADDRESS: 0.0.0.0
      BITRUBY_FRONTEND_URL: http://localhost:4200
      BITRUBY_VERIFICATION_SECRET_KEY: ${BITRUBY_VERIFICATION_SECRET_KEY}
      BITRUBY_VERIFICATION_API_KEY: ${BITRUBY_VERIFICATION_API_KEY}
      BITRUBY_VERIFICATION_CALLBACK_URL: 'https://webhook.cool/at/quaint-shampoo-70'
      BITRUBY_VERIFICATION_URL: 'https://stationapi.veriff.com/v1'
    networks:
      - bitruby_net
    extra_hosts:
      - dev.bitruby.kg : 10.0.1.15
    container_name: bitruby-users-app

  bitruby-auth-server:
    image: alexandershlyakhtin/auth-server:0.0.5
    ports:
      - 9000:9000
    depends_on:
      - bitruby-users-app
      - bitruby-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bitruby-postgres:5432/bitruby?currentSchema=users
      BITRUBY_AUTH_CLIENT_ID: ${BITRUBY_AUTH_CLIENT_ID}
      BITRUBY_AUTH_CLIENT_SECRET: ${BITRUBY_AUTH_CLIENT_SECRET}
      BITRUBY_FRONTEND_URL: http://localhost:4200
      SERVER_ADDRESS: 0.0.0.0
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://bitruby-auth-server:9000/auth/api/v1
    networks:
      - bitruby_net
    container_name: bitruby-auth-server

  bitruby-bybit-integrator:
    image: alexandershlyakhtin/bybit-integrator:0.0.3
    ports:
      - 8082:8082
    depends_on:
      - bitruby-postgres
      - bitruby-kafka
      - bitruby-redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bitruby-postgres:5432/bitruby?currentSchema=bybit
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: bitruby-kafka:9092
      BITRUBY_FRONTEND_URL: http://localhost:4200
      SPRING_DATA_REDIS_HOST: bitruby-redis
      BITRUBY_BYBIT_BYBIT_API_SECRET: ${BITRUBY_BYBIT_BYBIT_API_SECRET}
      BITRUBY_BYBIT_BYBIT_API_KEY: ${BITRUBY_BYBIT_BYBIT_API_KEY}
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - bitruby_net
    container_name: bitruby-bybit-integrator

  bitruby-notifications-service:
    image: alexandershlyakhtin/notifications-service:0.0.3
    depends_on:
      - bitruby-postgres
      - bitruby-kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: bitruby-kafka:9092
      BITRUBY_SMSTRIFFIC_LOGIN: ${BITRUBY_SMSTRIFFIC_LOGIN}
      BITRUBY_SMSTRIFFIC_PASSWORD: ${BITRUBY_SMSTRIFFIC_PASSWORD}
      BITRUBY_SENDSAY_APIKEY: ${BITRUBY_SENDSAY_APIKEY}
      BITRUBY_SENDSAY_APILOGIN: ${BITRUBY_SENDSAY_APILOGIN}
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - bitruby_net
    container_name: bitruby-notifications-service
